//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIWebTraining.Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competency
    {
        public int CompetencyID { get; set; }
        public int CompetencyGroupID { get; set; }
        public int CompetencyStatusID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> CompetencyTypeID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public Nullable<int> LevelID { get; set; }
    
        public virtual Competency tblCACompetency1 { get; set; }
        public virtual Competency tblCACompetency2 { get; set; }
    }
}
