//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIWebTraining.Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeJobTitle
    {
        public int JobTitleID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> JobTypeID { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public Nullable<short> ManagesOthers { get; set; }
        public Nullable<int> ReportsToID { get; set; }
        public Nullable<float> RequiresTravel { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    }
}
