//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIWebTraining.Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingTypes
    {
        public int TrainingTypeId { get; set; }
        public string TrainingType { get; set; }
        public string TrainingTypeCode { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string PositiveLabel { get; set; }
        public string NegativeLabel { get; set; }
    }
}
