//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIWebTraining.Objects.Models
{
    using System;
    
    public partial class User
    {
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public int UserID { get; set; }
        public string EmailAddress { get; set; }
        public string WinADName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
