//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIWebTraining.Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetencyDefHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetencyDefHeader()
        {
            this.tblCACompetency_AssessmentHeader = new HashSet<tblCACompetency_AssessmentHeader>();
        }
    
        public int CompDefHeaderID { get; set; }
        public Nullable<int> JobRoleID { get; set; }
        public string Description { get; set; }
        public Nullable<short> PassingGrade { get; set; }
        public Nullable<short> NotifyDays { get; set; }
        public Nullable<int> CompetencyStatusID { get; set; }
        public Nullable<short> RecurrenceQty { get; set; }
        public Nullable<int> UOMSchedulingRecurrenceID { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public Nullable<int> JobResponsibilityID { get; set; }
        public Nullable<short> Failure_RecurrenceQty { get; set; }
        public Nullable<int> Failure_UOMSchedulingRecurrenceID { get; set; }
        public string NotifyEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCACompetency_AssessmentHeader> tblCACompetency_AssessmentHeader { get; set; }
    }
}
