//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIWebTraining.Objects.Models
{
    using System;
    
    public partial class sp_CACompetency_GetAllEmployeeCompetencies_Result1
    {
        public string DateDue { get; set; }
        public string Description { get; set; }
        public string DefinedBy { get; set; }
        public Nullable<int> CompetencyDefHeaderID { get; set; }
    }
}
