//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIWebTraining.Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCACompetency_AssessmentHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCACompetency_AssessmentHeader()
        {
            this.tblCACompetency_AssessmentDetails = new HashSet<tblCACompetency_AssessmentDetails>();
        }
    
        public int CompetencyAssessmentID { get; set; }
        public Nullable<int> CompetencyDefHeaderID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CompetencyAssessorID { get; set; }
        public Nullable<System.DateTime> DateAssessed { get; set; }
        public Nullable<int> AssessmentGrade { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCACompetency_AssessmentDetails> tblCACompetency_AssessmentDetails { get; set; }
        public virtual CompetencyDefHeader tblCACompetency_DefinitionHeader { get; set; }
    }
}
